### ISSUE TITLE
unit tests?

### ISSUE THREAD

**Issue by winstonewert** [catb0t/mouse16#1]
You talk about unit tests in the comment on the top of mouse16.py, but I don't actually see any tests?

**Comment by catb0t** [comment]
https://github.com/catb0t/mousetest -- I'll add a link to them, sorry. This project is still heavily indev, but all the tests pass because they test the backend (the stack machine), not the parser & runtime, yet. Once I sort the parser so it works properly, I'll add unit testing for stdin/stdout and the parser.

**Comment by winstonewert** [comment]
Ok.

But now I have to ask, why are you putting the tests in a separate repo?

**Comment by catb0t** [comment]
I asked my programming teacher where he thought they should go, and he suggested a separate repo. I was pretty indifferent at the time, and personally I have a hard link to the unit tests in my local copy of `mouse16.git` (it's mentioned in `.gitignore`), so I guess I'll move them.

**Comment by winstonewert** [comment]
Well, I've never seen them put in a separate repo. Generally, it makes sense to have them in the same repo so that changes to test and changes to code go hand in hand. You know exactly which versions of tests went with which version of the code.

**Comment by catb0t** [comment]
Yeah, I suppose that makes more sense.
